project:
  type: website

website:
  title: "ISSS608 Visual Analytics & Applications"
  navbar:
    left: 
      - text: Hands-on Exercises
        menu: 
          - text: Hands-on Exercise 1
            href: xx
          - text: Hands-on Exercise 2
            href: xx
          - text: Hands-on Exercise 3
            href: xx
          - text: Hands-on Exercise 4
            href: xx
          - text: Hands-on Exercise 5
            href: xx
      - text: In-class Exercises
        menu: 
          - text: In-class Exercise 1
            href: xx
          - text: In-class Exercise 2
            href: xx
          - text: In-class Exercise 3
            href: xx
          - text: In-class Exercise 4
            href: xx
          - text: In-class Exercise 5
            href: xx
          - text: In-class Exercise 6
            href: xx
      - text: Take-Home Exercises
        menu: 
          - text: Take-Home Exercise 1
            href: xx
          - text: Take-Home Exercise 2
            href: xx
    right:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About

format:
  html:
    theme: spacelab
    css: styles.css
    toc: true

editor: visual
