project:
  type: website

website:
  title: "ISSS608 Visual Analytics & Applications"
  navbar:
    left: 
      - text: Hands-on Exercises
        menu: 
          - text: Hands-on Exercise 1
            href: Hands-on_Exercies/Hands-on_Ex1/Hands-on_Ex1.qmd
          - text: Hands-on Exercise 2
            href: Hands-on_Exercies/Hands-on_Ex2/Hands-on_Ex2.qmd
          - text: Hands-on Exercise 3
            href: Hands-on_Exercies/Hands-on_Ex3/Hands-on_Ex3.qmd
          - text: Hands-on Exercise 3-2
            href: Hands-on_Exercies/Hands-on_Ex3/Hands-on_Ex3-2.qmd
          - text: Hands-on Exercise 4-1
            href: Hands-on_Exercies/Hands-on_Ex4/Hands-on_Ex4-1.qmd
          - text: Hands-on Exercise 4-2
            href: Hands-on_Exercies/Hands-on_Ex4/Hands-on_Ex4-2.qmd 
          - text: Hands-on Exercise 4-3
            href: Hands-on_Exercies/Hands-on_Ex4/Hands-on_Ex4-3.qmd
      - text: In-class Exercises
        menu: 
          - text: In-class Exercise 1
            href: In-class_Exercies/In-class_Ex1/In-class_Ex1.qmd
          - text: In-class Exercise 3
            href: https://public.tableau.com/app/profile/shu.min.han/viz/In-class_Ex3_16827468503590/SalesvsProfit
          - text: In-class Exercise 3-2
            href: In-class_Exercies/In-class_Ex3/In-class_Ex3.qmd
          - text: In-class Exercise 4
            href: In-class_Exercies/In-class_Ex4/In-class_Ex4.qmd
          - text: In-class Exercise 6
            href: xx
      - text: Take-Home Exercises
        menu: 
          - text: Take-Home Exercise 1
            href: Take-home_Exercise/Take-home_Ex1/Take-home_Ex1.qmd
          - text: Take-Home Exercise 2
            href: xx
      - text: Group Project
        menu: 
          - text: R shinny Project
            href: xx

    right:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About

format:
  html:
    theme: spacelab
    css: styles.css
    toc: true

editor: visual
