---
title: "Take-home_Ex3"
editor: visual
author: "Han Shumin"
date: "2 Jun 2023"
date-modified: "`r Sys.Date()`"
format:
  html:
    code-fold: true
    code-summary: "Show the code"
execute: 
  echo: true
  eval: true
  warning: false
---

```{r}
pacman::p_load(jsonlite, tidygraph, ggraph, visNetwork, graphlayouts, ggforce, tidytext, tidyverse)
```

```{r}
MC3 <- fromJSON("data/MC3.json")
```

```{r}
MC3_nodes <- as_tibble(MC3$nodes) %>%
  # distinct() %>%
  mutate(country = as.character(country),
         id = as.character(id),
         product_services = 
           as.character(product_services),
         revenue_omu = 
           as.numeric(as.character(revenue_omu)),
         type = as.character(type)) %>%
  select(id, country, type, revenue_omu, product_services)

glimpse(MC3_nodes)
```

```{r}
MC3_edges <- as_tibble(MC3$links) %>%
  distinct() %>%
  mutate(source = 
           as.character(source),
         target = 
           as.character(target),
         type = 
           as.character(type)) %>%
  group_by(source, target, type) %>%
  summarise(weights = n()) %>%
  filter(source != target) %>%
  ungroup()

glimpse(MC3_edges)  
```


